version: '3.8'

services:
  cody-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cody-app
    restart: unless-stopped
    env_file:
      - key.env
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_CONFIG_LOCATION=classpath:/application.properties
#      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
#      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.SQLServerDialect
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_SHOW_SQL=true
#      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
#      - SECRET_KEY=${SECRET_KEY}
#      - EXPIRATION=${EXPIRATION}
#      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
#      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=Asia/Bangkok
#      - SPRING_JACKSON_DATE_FORMAT=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
#      - SPRING_JACKSON_TIME_ZONE=Asia/Bangkok